# Generated by Django 4.2.7 on 2023-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('gas_level', models.FloatField()),
                ('flame', models.BooleanField()),
                ('relay1', models.BooleanField()),
                ('relay2', models.BooleanField()),
                ('switch1', models.BooleanField()),
                ('switch2', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
