# Generated by Django 4.2.7 on 2023-11-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchendata',
            old_name='relay2',
            new_name='fan',
        ),
        migrations.RenameField(
            model_name='kitchendata',
            old_name='relay1',
            new_name='lamp',
        ),
    ]
